import type { LLMProvider, LLMRequest, LLMResult } from '../types';
import { estimateTokens } from '../cost';
import { hash32 } from '../../utils';

/**
 * Deterministic offline provider. Produces schema-correct output for every
 * pipeline task so the whole system is runnable and testable without keys.
 * Content is clearly synthetic and every article it produces is flagged.
 */

function seeded(seed: string) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (Math.imul(31, h) + seed.charCodeAt(i)) | 0;
  return () => {
    h = (Math.imul(1103515245, h) + 12345) | 0;
    return ((h >>> 16) & 0x7fff) / 0x7fff;
  };
}

const TOPIC_SHAPES = [
  { t: 'Best {niche} for {audience}', intent: 'COMMERCIAL', type: 'BEST_OF' },
  { t: 'How to choose {niche} without overpaying', intent: 'INFORMATIONAL', type: 'HOW_TO' },
  { t: '{niche}: free versus paid, what actually differs', intent: 'COMPARISON', type: 'COMPARISON' },
  { t: 'Alternatives to the most popular {niche}', intent: 'COMMERCIAL', type: 'ALTERNATIVES' },
  { t: 'A plain-English guide to {niche}', intent: 'INFORMATIONAL', type: 'EXPLAINER' },
  { t: '{niche} pricing compared', intent: 'COMMERCIAL', type: 'COMPARISON' },
  { t: 'Common mistakes when adopting {niche}', intent: 'INFORMATIONAL', type: 'STANDARD' },
  { t: 'What changed in {niche} this year', intent: 'NEWS', type: 'NEWS' },
];

function discoverTopics(meta: Record<string, unknown>) {
  const niche = String(meta.niche ?? 'AI tools');
  const audience = String(meta.audience ?? 'small teams');
  const count = Math.min(Number(meta.count ?? 8), TOPIC_SHAPES.length);
  const rand = seeded(`${niche}:${String(meta.cycle ?? '')}`);
  return JSON.stringify(
    TOPIC_SHAPES.slice(0, count).map((shape, i) => ({
      title: shape.t.replace('{niche}', niche).replace('{audience}', audience),
      angle: `Practical, decision-focused coverage of ${niche} written for ${audience}.`,
      intent: shape.intent,
      contentType: shape.type,
      primaryKeyword: `${niche} ${['best', 'guide', 'comparison', 'alternatives', 'pricing'][i % 5]}`.toLowerCase(),
      secondaryKeywords: [`${niche} for ${audience}`, `cheap ${niche}`, `${niche} review`],
      commercialScore: Math.round(30 + rand() * 65),
      difficulty: Math.round(20 + rand() * 60),
      rationale: 'Matches an unserved decision-stage query in the configured niche.',
    })),
  );
}

function synthResearch(meta: Record<string, unknown>) {
  const topic = String(meta.topic ?? 'the topic');
  return JSON.stringify({
    summary: `Synthetic research bundle for "${topic}". Generated by the mock provider - no live sources were consulted.`,
    facts: [
      { claim: 'Entry pricing in this category clusters in a low monthly band.', value: 'varies by vendor', category: 'pricing', isVolatile: true, confidence: 0.4, verdict: 'UNVERIFIED' },
      { claim: 'The category has consolidated around a handful of established vendors.', category: 'company', isVolatile: false, confidence: 0.5, verdict: 'UNVERIFIED' },
      { claim: 'Free tiers generally impose export or watermark limits.', category: 'feature', isVolatile: true, confidence: 0.45, verdict: 'UNVERIFIED' },
    ],
    conflicts: 'Mock mode: no cross-source verification was performed.',
    sufficient: true,
  });
}

function writeArticle(meta: Record<string, unknown>) {
  const title = String(meta.title ?? 'Untitled');
  const sections: string[] = Array.isArray(meta.sections) ? (meta.sections as string[]) : ['Introduction', 'Main Explanation', 'Conclusion'];
  const target = Number(meta.targetWords ?? 1400);
  const perSection = Math.max(90, Math.floor(target / Math.max(1, sections.length)));
  const rand = seeded(title);

  const bank = [
    'The practical question is not which tool is objectively best, but which constraint you are optimising against.',
    'Most buyers over-index on feature lists and under-index on export limits, which is where the real friction shows up.',
    'Pricing pages describe intent rather than experience, and the meaningful differences usually appear at the seat and usage tiers.',
    'A shortlist of two or three options tested against your own workflow beats any ranked list assembled in the abstract.',
    'Where a claim below could not be tied to a verifiable source it is marked as unverified rather than stated as fact.',
    'Migration cost is the quiet variable, because the cheapest option is rarely cheapest once existing assets have to move.',
  ];
  const filler = (n: number) => {
    const out: string[] = [];
    let words = 0;
    while (words < n) {
      const s = bank[Math.floor(rand() * bank.length)];
      out.push(s);
      words += s.split(' ').length;
    }
    return out.join(' ');
  };

  let md = '> **Sample content.** This article was produced by the offline mock provider for development and contains no verified information.\n\n';
  for (const section of sections) {
    if (section === 'Introduction') {
      md += `${filler(perSection)}\n\n`;
      continue;
    }
    md += `## ${section}\n\n`;
    if (section === 'Key Takeaways' || section === 'Pros & Cons') {
      md += `- ${filler(14)}\n- ${filler(14)}\n- ${filler(14)}\n\n`;
    } else if (section === 'Step-by-Step Guide') {
      md += `1. ${filler(18)}\n2. ${filler(18)}\n3. ${filler(18)}\n\n`;
    } else if (section === 'Comparison' || section === 'Pricing') {
      md += '| Option | Best for | Starting tier |\n| --- | --- | --- |\n| Option A | Solo users | Free tier available |\n| Option B | Small teams | Paid, tier varies |\n| Option C | Heavy exports | Paid, tier varies |\n\n';
      md += `${filler(Math.max(60, perSection - 40))}\n\n`;
    } else if (section === 'FAQs') {
      md += `### Is a free tier enough to start?\n\n${filler(45)}\n\n### How often do prices change?\n\n${filler(45)}\n\n`;
    } else {
      md += `${filler(perSection)}\n\n`;
    }
  }
  return md;
}

function reviewArticle(meta: Record<string, unknown>) {
  const rand = seeded(String(meta.title ?? 'x') + String(meta.attempt ?? 1));
  const base = Number(meta.attempt ?? 1) > 1 ? 88 : 80;
  const s = (n: number) => Math.min(98, Math.max(50, Math.round(n + rand() * 10)));
  return JSON.stringify({
    accuracy: s(base), usefulness: s(base), originality: s(base - 6), readability: s(base + 6),
    intentMatch: s(base + 2), structure: s(base + 4), seo: s(base), factReliability: s(base - 4),
    internalLinking: s(base - 8), spamRisk: Math.round(6 + rand() * 10),
    weakSections: base < 85 ? ['Main Explanation'] : [],
    feedback: 'Mock review. Tighten the opening and ground volatile claims in research before publishing.',
    unverifiedClaims: [],
  });
}

function seoMeta(meta: Record<string, unknown>) {
  const title = String(meta.title ?? 'Untitled');
  return JSON.stringify({
    seoTitle: title.slice(0, 58),
    metaDesc: `${title}: a practical, research-backed breakdown of what matters, what does not, and how to decide.`.slice(0, 155),
    ogTitle: title.slice(0, 60),
    ogDesc: `A clear, jargon-free look at ${title.toLowerCase()}.`.slice(0, 150),
    excerpt: `A practical breakdown of ${title.toLowerCase()}, written for people who need to make a decision rather than browse a feature list.`,
    tags: ['guides', 'tools', 'comparison'],
  });
}

export class MockLLMProvider implements LLMProvider {
  id = 'mock';
  isConfigured() {
    return true;
  }

  async complete(model: string, req: LLMRequest): Promise<LLMResult> {
    const started = Date.now();
    const meta = req.meta ?? {};
    let text: string;
    switch (req.task) {
      case 'TOPIC_DISCOVERY': text = discoverTopics(meta); break;
      case 'RESEARCH_SYNTHESIS': text = synthResearch(meta); break;
      case 'ARTICLE_WRITING':
      case 'ARTICLE_REWRITE': text = writeArticle(meta); break;
      case 'QUALITY_REVIEW': text = reviewArticle(meta); break;
      case 'SEO_METADATA': text = seoMeta(meta); break;
      case 'IMAGE_PROMPT':
        text = `Abstract editorial cover illustration for "${String(meta.title ?? '')}", flat geometric shapes, muted palette.`;
        break;
      case 'REFRESH_DIFF':
        text = JSON.stringify({ needsUpdate: false, reasons: [], changedSections: [] });
        break;
      case 'FACT_CHECK':
        text = JSON.stringify({ verdicts: [], unverified: [] });
        break;
      default:
        text = JSON.stringify({ ok: true, note: `mock output for ${req.task}` });
    }
    return {
      text,
      provider: 'mock',
      model: model || 'mock-model',
      inputTokens: estimateTokens(req.prompt + (req.system ?? '')),
      outputTokens: estimateTokens(text),
      latencyMs: Date.now() - started,
    };
  }

  /** Deterministic pseudo-embedding: stable across runs, adequate for dedupe. */
  async embed(text: string): Promise<number[]> {
    const dims = 256;
    const out = new Array<number>(dims).fill(0);
    for (const tok of text.toLowerCase().split(/\W+/).filter(Boolean)) {
      out[parseInt(hash32(tok), 36) % dims] += 1;
    }
    const norm = Math.sqrt(out.reduce((a, b) => a + b * b, 0)) || 1;
    return out.map((v) => v / norm);
  }
}
