import Link from 'next/link';
import { videoSnapshot } from '@/lib/pipeline/article-video';
import { videoServiceStatus } from '@/lib/video/mpt-client';
import { getSettings } from '@/lib/settings';
import { wordBudget } from '@/lib/video/narration';
import { formatDate, truncate } from '@/lib/utils';
import { StatCard, PageHeader, TableWrap } from '@/components/admin/stat-card';
import { Th, Td, Section } from '@/components/admin/form-fields';
import { Badge } from '@/components/ui/badge';
import { ActionButton } from '@/components/admin/action-form';
import { CopyButton } from '@/components/admin/copy-button';
import { VIDEO_TONES } from '@/components/admin/video-panel';
import { EmptyState } from '@/components/ui/empty-state';
import { articleHref } from '@/components/site/article-card';
import {
  retryVideoAction, regenerateVideoAction, refreshVideoStatusAction,
  markVideoPublishedAction, deleteVideoAction, pingVideoServiceAction,
} from '@/actions/videos';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Videos' };

function ConfigRow({ label, value, tone }: { label: string; value: string; tone: 'green' | 'amber' | 'neutral' }) {
  return (
    <div className="flex items-center justify-between gap-3 py-2">
      <dt className="text-sm text-ink-500">{label}</dt>
      <dd><Badge tone={tone}>{value}</Badge></dd>
    </div>
  );
}

export default async function VideosPage() {
  const [snapshot, settings] = await Promise.all([videoSnapshot(), getSettings()]);
  // Redacted server config — contains no API key and no credentials.
  const service = videoServiceStatus();

  return (
    <>
      <PageHeader
        title="Short-form videos"
        description="Generated by MoneyPrinterTurbo, which runs as a separate service. Article publishing never waits on video — if the service is offline, articles still go live and video jobs retry independently."
        actions={<ActionButton action={pingVideoServiceAction} label="Check connection" pendingLabel="Pinging…" />}
      />

      {!service.enabled && (
        <div className="card mb-6 border-amber-300 bg-amber-50 p-4 text-sm dark:border-amber-900 dark:bg-amber-950/30">
          <p className="font-medium text-amber-900 dark:text-amber-300">Video generation is disabled</p>
          <p className="mt-1 text-amber-800 dark:text-amber-400">
            Set <code>MPT_ENABLED=true</code> and point <code>MPT_API_URL</code> at your MoneyPrinterTurbo instance
            (default <code>http://127.0.0.1:8080</code>). Nothing else in the platform is affected while this is off.
          </p>
        </div>
      )}

      <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
        <StatCard label="Queued" value={snapshot.queued} />
        <StatCard label="Generating" value={snapshot.generating} tone={snapshot.generating > 0 ? 'warning' : 'default'} />
        <StatCard label="Completed" value={snapshot.completed} tone="success" />
        <StatCard label="Failed" value={snapshot.failed} tone={snapshot.failed > 0 ? 'danger' : 'default'} />
        <StatCard label="Published" value={snapshot.published} />
        <StatCard label="Created today" value={snapshot.today} hint={`cap ${settings.videoMaxPerDay || '∞'}`} />
      </div>

      <div className="mb-6 grid gap-6 lg:grid-cols-2">
        <Section title="MoneyPrinterTurbo" description="Read from server environment variables. Restart the app and the worker after changing them.">
          <dl className="divide-y divide-ink-200/70 dark:divide-ink-800/70">
            <ConfigRow label="Enabled" value={service.enabled ? 'enabled' : 'disabled'} tone={service.enabled ? 'green' : 'neutral'} />
            <ConfigRow
              label="API URL"
              value={service.endpointConfigured ? 'configured' : 'missing'}
              tone={service.endpointConfigured ? 'green' : 'amber'}
            />
            <ConfigRow label="Auto video" value={service.autoVideo ? 'on' : 'off'} tone={service.autoVideo ? 'green' : 'neutral'} />
            <ConfigRow
              label="Auto retry"
              value={service.autoRetry ? `on · max ${service.maxRetries}` : 'off'}
              tone={service.autoRetry ? 'green' : 'neutral'}
            />
            <ConfigRow
              label="Public base URL"
              value={service.publicBaseConfigured ? 'configured' : 'using API URL'}
              tone={service.publicBaseConfigured ? 'green' : 'neutral'}
            />
          </dl>
          <p className="mt-3 text-xs leading-relaxed text-ink-500">
            Endpoint <code>{service.baseUrl}</code>. Connection is only checked when you press
            “Check connection” — nothing polls the service for liveness.
          </p>
        </Section>

        <Section title="Output settings" description="Applied to every new video job.">
          <dl className="divide-y divide-ink-200/70 dark:divide-ink-800/70 text-sm">
            <div className="flex items-center justify-between gap-3 py-2">
              <dt className="text-ink-500">Format</dt>
              <dd>{service.aspect} · {service.quality} · {settings.videoSource}</dd>
            </div>
            <div className="flex items-center justify-between gap-3 py-2">
              <dt className="text-ink-500">Narration</dt>
              <dd>~{service.durationSec}s · {wordBudget(service.durationSec).min}–{wordBudget(service.durationSec).max} words</dd>
            </div>
            <div className="flex items-center justify-between gap-3 py-2">
              <dt className="text-ink-500">Polling</dt>
              <dd>every {Math.round(service.pollIntervalMs / 1000)}s · give up after {service.maxPollMinutes}m</dd>
            </div>
            <div className="flex items-center justify-between gap-3 py-2">
              <dt className="text-ink-500">Subtitles / music</dt>
              <dd>{settings.videoSubtitles ? 'on' : 'off'} · {settings.videoBgMusic ? 'on' : 'off'}</dd>
            </div>
          </dl>
          <p className="mt-3 text-xs leading-relaxed text-ink-500">
            Auto generation on publish is {settings.videoEnabled && settings.videoOnPublish && service.autoVideo ? 'on' : 'off'}.
            Category eligibility and the daily cap live in Site Settings.
          </p>
        </Section>
      </div>

      {snapshot.recent.length === 0 ? (
        <EmptyState
          title="No videos yet"
          hint="A video job is created automatically when an article reaches PUBLISHED, provided video generation is enabled and the article's category is eligible."
          action={<Link className="btn-primary" href="/admin/articles?status=PUBLISHED">View published articles</Link>}
        />
      ) : (
        <TableWrap>
          <thead>
            <tr>
              <Th>Article / video</Th><Th>Status</Th><Th>Task</Th><Th>Video</Th>
              <Th>Created</Th><Th>Completed</Th><Th className="text-right">Actions</Th>
            </tr>
          </thead>
          <tbody>
            {snapshot.recent.map((v) => (
              <tr key={v.id}>
                <Td>
                  <Link href={`/admin/articles/${v.article.id}`} className="font-medium hover:text-accent-600">
                    {truncate(v.article.title, 52)}
                  </Link>
                  {v.videoTitle && <p className="mt-0.5 text-xs text-ink-600 dark:text-ink-400">{truncate(v.videoTitle, 70)}</p>}
                  <p className="mt-0.5 text-xs text-ink-500">
                    {v.aspect} · {v.source} · {v.language} · v{v.version}
                    {v.script ? ` · ${v.script.split(/\s+/).length} words` : ''}
                    {v.attempts > 0 ? ` · retries ${v.attempts}/${v.maxAttempts}` : ''}
                  </p>
                  {v.error && <p className="mt-1 text-xs text-red-600 dark:text-red-400">{truncate(v.error, 160)}</p>}
                  {(v.script || v.videoDescription) && (
                    <details className="mt-1">
                      <summary className="cursor-pointer text-xs text-ink-500">Script &amp; description</summary>
                      {v.videoDescription && (
                        <p className="mt-1 max-w-lg text-xs italic text-ink-500">{v.videoDescription}</p>
                      )}
                      {v.script && (
                        <p className="mt-1 max-w-lg text-xs text-ink-600 dark:text-ink-400">{v.script}</p>
                      )}
                      {v.scriptTerms.length > 0 && (
                        <p className="mt-1 text-xs text-ink-500">Terms: {v.scriptTerms.join(', ')}</p>
                      )}
                    </details>
                  )}
                </Td>
                <Td><Badge tone={VIDEO_TONES[v.status] ?? 'neutral'}>{v.status.toLowerCase()}</Badge></Td>
                <Td>
                  {v.taskId ? (
                    <div className="flex flex-col items-start gap-1">
                      <code className="text-xs text-ink-500">{truncate(v.taskId, 12)}</code>
                      <CopyButton value={v.taskId} label="Copy" />
                    </div>
                  ) : (
                    <span className="text-ink-500">—</span>
                  )}
                </Td>
                <Td>
                  {v.videoUrl ? (
                    // Proxied through AutoPress: the browser never needs a route
                    // to MoneyPrinterTurbo, which has no authentication.
                    <a href={`/api/admin/videos/${v.id}/file`} target="_blank" rel="noopener noreferrer"
                      className="text-accent-700 hover:underline dark:text-accent-400">Open video</a>
                  ) : v.status === 'COMPLETED' ? (
                    <span className="text-xs text-amber-700 dark:text-amber-400">No public URL</span>
                  ) : (
                    <span className="text-ink-500">—</span>
                  )}
                  {v.platform && <p className="text-xs text-ink-500">on {v.platform}</p>}
                  <Link href={articleHref({ slug: v.article.slug, category: v.article.category })}
                    target="_blank" rel="noopener noreferrer"
                    className="mt-1 block text-xs text-ink-500 hover:text-ink-800 dark:hover:text-ink-200">
                    View article ↗
                  </Link>
                </Td>
                <Td className="whitespace-nowrap text-xs text-ink-500">
                  {formatDate(v.createdAt, { dateStyle: 'short', timeStyle: 'short' })}
                </Td>
                <Td className="whitespace-nowrap text-xs text-ink-500">
                  {v.completedAt ? formatDate(v.completedAt, { dateStyle: 'short', timeStyle: 'short' }) : '—'}
                </Td>
                <Td>
                  <div className="flex flex-wrap justify-end gap-1.5">
                    {v.status === 'GENERATING' && (
                      <ActionButton action={refreshVideoStatusAction} label="Check status" fields={{ id: v.id }} pendingLabel="Checking…" />
                    )}
                    {(v.status === 'FAILED' || v.status === 'QUEUED') && (
                      <ActionButton action={retryVideoAction} label="Retry" variant="primary" fields={{ id: v.id }} pendingLabel="Retrying…" />
                    )}
                    <ActionButton action={regenerateVideoAction} label="Regenerate" fields={{ id: v.id }}
                      pendingLabel="Queueing…"
                      confirmText="Rebuild the script and render a new video for this article?" />
                    {v.status === 'COMPLETED' && v.videoUrl && (
                      <ActionButton action={markVideoPublishedAction} label="Mark published"
                        fields={{ id: v.id, platform: 'manual' }} />
                    )}
                    <ActionButton action={deleteVideoAction} label="Delete" variant="danger" fields={{ id: v.id }}
                      confirmText="Delete this video record? A new one can then be generated for the article." />
                  </div>
                </Td>
              </tr>
            ))}
          </tbody>
        </TableWrap>
      )}
    </>
  );
}
